issues:
  exclude-rules:
    # Exclude lostcancel govet rule specifically for requester.go
    # Since we purpocefully do that. See comments in code.
    - path: runner/requester.go
      text: "lostcancel"
    # TODO Look into fixing time.Tick() usage SA1015 in worker.go
    - path: runner/worker.go
      text: "SA1015"