issues:
  exclude-rules:
    # Exclude lostcancel govet rule specifically for requester.go
    # Since we purpocefully do that. See comments in code.
    - path: runner/requester.go
      text: "lostcancel"
      linters:
        - govet