version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go test ./...
workflows:
  version: 2
  github_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
                - heroku
